import { Status } from "@/helpers";
import { hashPassword } from "@/tests/utils";

const generateMockEmployee = async (overrides = {}) => ({
  staffId: 1,
  staffFName: "John",
  staffLName: "Doe",
  dept: "Development",
  position: "Developer",
  country: "USA",
  email: "test@example.com",
  hashedPassword: await hashPassword("test-password"),
  reportingManager: null,
  reportingManagerName: null,
  tempReportingManager: null,
  tempReportingManagerName: null,
  role: 1,
  ...overrides,
});

const generateMockEmployeeTest = async (overrides = {}) => ({
  staffId: 140003,
  staffFName: "Janice",
  staffLName: "Chan",
  dept: "Sales",
  position: "Account Manager",
  country: "Singapore",
  email: "test@example.com",
  hashedPassword: await hashPassword("test-password"),
  reportingManager: 140894,
  reportingManagerName: "Rahim Khalid",
  role: 2,
  ...overrides,
});

const mockRequestData = {
  [Status.PENDING]: {
    staffId: 140003,
    staffName: "Janice Chan",
    reportingManager: 140894,
    managerName: "Rahim Khalid",
    dept: "Sales",
    requestedDate: "2024-10-08T00:00:00.000Z",
    requestType: "FULL",
    reason: "Raining",
    status: "PENDING",
    requestId: 22,
  },
  [Status.APPROVED]: {
    staffId: 140003,
    staffName: "Janice Chan",
    reportingManager: 140894,
    managerName: "Rahim Khalid",
    dept: "Sales",
    position: "Account Manager",
    requestedDate: "2024-10-08T00:00:00.000Z",
    requestType: "FULL",
    reason: "Raining",
    status: "APPROVED",
    requestId: 22,
  },
  [Status.REJECTED]: {
    staffId: 140003,
    staffName: "Janice Chan",
    reportingManager: 140894,
    managerName: "Rahim Khalid",
    dept: "Sales",
    position: "Account Manager",
    requestedDate: "2024-10-08T00:00:00.000Z",
    requestType: "FULL",
    reason: "Raining",
    status: "REJECTED",
    requestId: 22,
  },
  testing: {
    staffId: 140003,
    staffName: "Janice Chan",
    reportingManager: 140894,
    managerName: "Rahim Khalid",
    dept: "Sales",
    position: "Account Manager",
    requestedDate: new Date(),
    requestType: "FULL",
    reason: "Raining",
    status: "REJECTED",
    requestId: 22,
  },
};

const mockWithdrawalData = {
  requestId: 22,
  staffId: 140003,
  staffName: "Janice Chan",
  reportingManager: 140894,
  managerName: "Rahim Khalid",
  dept: "Sales",
  position: "Account Manager",
  reason: "Plans cancelled",
  requestedDate: new Date(),
  requestType: "AM",
  withdrawalId: 1,
  status: "PENDING",
};

export {
  generateMockEmployee,
  generateMockEmployeeTest,
  mockRequestData,
  mockWithdrawalData,
};
